version: '2.4'
services:

  example-db:
    image: tiredofit/mariadb:10.6
    container_name: example-db
    volumes:
      - ./db:/var/lib/mysql
      - ./logs:/logs
    environment:
      - DB_NAME=database
      - DB_USER=user
      - DB_PASS=password
      - ROOT_PASS=rootpassword
    restart: always
